### ISSUE TITLE
Simplify the ByteBuffer extension. Don't use memory binding API.s

### ISSUE THREAD

**Issue by atrick** [SwiftNIOExtras/swift-nio-irc#3]
```
self.withVeryUnsafeBytes { rbpp in
      let mrbpp  = UnsafeMutableRawBufferPointer(mutating: rbpp)
      let base   = mrbpp.baseAddress!.assumingMemoryBound(to: UInt8.self)
                        .advanced(by: index)
// ...
      cursor -= 1
      cursor.pointee = 45 // -
```

The fact that you need to use the `mutating` `UnsafeMutableRawBufferPointer` initializer is a bug in the SwiftNIO API. Could you file an issue over there with your use case?

Please don't use `assumingMemoryBound` to access the bytes in `ByteBuffer`. It's a dangerous misuse of that API.

You can replace everything above with:
```
index -= 1
rbpp[index] = 45
```

You can drop down to `let cursor = rbpp.baseAddress!` if you want, but you lose debug build bounds checking.

**Comment by helje5** [comment]
Whoops, I completely missed that issue, sorry. Thanks for reporting, I'll have a look :-)

**Comment by helje5** [comment]
Better late than never, but this is fixed now 😄
