### ISSUE TITLE
IRCMode +x not supported

### ISSUE THREAD

**Issue by drallgood** [SwiftNIOExtras/swift-nio-irc#5]
Geekshed assigns "+iRx" but "x" is not supported

**Comment by helje5** [comment]
That would be in https://github.com/SwiftNIOExtras/swift-nio-irc/blob/develop/Sources/NIOIRC/Model/IRCChannelMode.swift#L15

What is `x`, need to DDG. Hm, what is `x`, there is only `X`.

**Comment by helje5** [comment]
https://help.undernet.org/faq.php?what=usermodes#05

> +x is a usermode that allows logged in users to hide their real host, replacing it with @username.users.undernet.org

**Comment by helje5** [comment]
Oh, it's a user mode, so this one: https://github.com/SwiftNIOExtras/swift-nio-irc/blob/develop/Sources/NIOIRC/Model/IRCUserMode.swift 

https://www.unrealircd.org/docs/User_Modes
> x - Gives you a hidden / cloaked hostname.

**Comment by helje5** [comment]
OK, it's in, untested of course.
