### ISSUE TITLE
IRCNickName / IRCUserID is nil if user name starts with a digit.

### ISSUE THREAD

**Issue by gbeaman** [SwiftNIOExtras/swift-nio-irc#6]
Technically a violation of the IRC spec, but some platforms such as Twitch's IRC chatrooms allow usernames to start with a digit. Currently swift-nio-irc won't make IRCNickName and related objects due to the validation, which limits use of the library on such platforms.

**Comment by helje5** [comment]
Should be fixed in 0.8.1, thanks for reporting.
